# zenn-app/docker-compose.yml
version: "3"

services:
  # ===============================
  # 1. DB
  # ===============================
  db:
    container_name: db
    image: mysql:5.7.30
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      app_net:
        ipv4_address: '172.20.0.2'

  # ===============================
  # 2. backend(rails)
  # ===============================
  backend:
    container_name: backend
    build: ./backend/
    image: backend
    # 1. rails s
    command: bundle exec rails server -b 0.0.0.0
    tty: true
    stdin_open: true
    # 2. volumesは色々あるね
    volumes:
      - ./backend:/app:cached # cached機能を使う（Railsの反応が速くなる）
      - bundle_data:/usr/local/bundle:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
    # 3. ホスト側は5000番で公開
    ports:
      - 5000:3000 # ポートフォワード

    # 4. network（frontと同じネットワークにしてるっぽい）
    networks:
      app_net:
        ipv4_address: '172.20.0.3'

  # ===============================
  # frontend
  # ===============================
  frontend:
    container_name: front
    build: ./frontend/
    image: frontend
    volumes:
      - ./frontend:/app
    # 1. portは3000番
    ports:
      - 3000:3000
    # 2. nuxtを起動
    command: "npm run dev"
    # 3. network接続
    networks:
      app_net:
        ipv4_address: '172.20.0.4'

# ===============================
# network
# ===============================
# network（frontと同じネットワークにしてるっぽい）
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24


# ===============================
# volumes
# ===============================
volumes:
  mysql_data:
  bundle_data:
